spring:
  datasource:
    url: jdbc:h2:mem:automobili
    username: root
    password: toor
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /all/console